# Generated by Django 6.0.2 on 2026-05-13 15:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPIDashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('SECRETARY', 'Secrétaire'), ('STOCK_MANAGER', 'Gestionnaire Stock'), ('PRODUCTION_MANAGER', 'Responsable Production'), ('TECHNICIAN', 'Technicien')], max_length=50, unique=True, verbose_name='Rôle utilisateur')),
                ('show_revenue', models.BooleanField(default=True, verbose_name='Afficher revenu')),
                ('show_orders', models.BooleanField(default=True, verbose_name='Afficher commandes')),
                ('show_production', models.BooleanField(default=True, verbose_name='Afficher production')),
                ('show_stock', models.BooleanField(default=True, verbose_name='Afficher stock')),
                ('show_resources', models.BooleanField(default=True, verbose_name='Afficher ressources')),
                ('default_chart_type', models.CharField(choices=[('line', 'Line'), ('bar', 'Bar'), ('pie', 'Pie')], default='line', max_length=20, verbose_name='Type de graphique par défaut')),
                ('refresh_interval_minutes', models.PositiveIntegerField(default=15, verbose_name='Intervalle de rafraîchissement (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Configuration KPI Dashboard',
                'verbose_name_plural': 'Configurations KPI Dashboard',
            },
        ),
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('REVENUE', 'Revenu total'), ('ORDERS_PENDING', 'Commandes en attente'), ('ORDER_COMPLETION', 'Taux de complétion'), ('PRODUCTION_ACTIVE', 'Productions actives'), ('PRODUCTION_LEAD_TIME', 'Temps de cycle'), ('STOCK_VALUE', 'Valeur stock'), ('STOCK_LOW', 'Articles en rupture'), ('RESOURCE_UTIL', 'Taux utilisation ressources')], db_index=True, max_length=50, verbose_name='Type de métrique')),
                ('metric_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valeur')),
                ('unit', models.CharField(blank=True, help_text='ex: CFA, %, count, days', max_length=50, verbose_name='Unité')),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Capturé le')),
                ('metadata', models.JSONField(blank=True, help_text='Additional context as JSON', null=True, verbose_name='Métadonnées')),
            ],
            options={
                'verbose_name': 'Snapshot KPI',
                'verbose_name_plural': 'Snapshots KPI',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['metric_type', '-captured_at'], name='dashboard_k_metric__39d2d4_idx')],
            },
        ),
    ]
