# Generated by Django 6.0.2 on 2026-03-01 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACTIVE', 'En cours'), ('PAUSED', 'Mise en pause'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('produced_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité produite')),
                ('defective_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité défectueuse')),
                ('quality_notes', models.TextField(blank=True, verbose_name='Notes de qualité')),
                ('assigned_team', models.CharField(blank=True, max_length=255, verbose_name='Équipe assignée')),
                ('line_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de ligne')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='commandes.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'Productions',
                'ordering': ['-created_at'],
            },
        ),
    ]
