# Generated by Django 6.0.2 on 2026-03-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du rapport')),
                ('report_type', models.CharField(choices=[('SALES', 'Ventes'), ('PRODUCTION', 'Production'), ('STOCK', 'Stock'), ('FINANCIAL', 'Financier'), ('OPERATIONS', 'Opérations')], max_length=20, verbose_name='Type de rapport')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Données')),
                ('generated_by', models.CharField(blank=True, max_length=255, verbose_name='Généré par')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
