# Generated by Django 6.0.2 on 2026-05-13 15:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(db_index=True, max_length=255, verbose_name='Nom de la métrique')),
                ('metric_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valeur')),
                ('unit', models.CharField(blank=True, help_text='ex: CFA, %, units', max_length=50, verbose_name='Unité')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Ligne de rapport',
                'verbose_name_plural': 'Lignes de rapport',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Généré le'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('SALES', 'Ventes'), ('PRODUCTION', 'Production'), ('STOCK', 'Stock'), ('FINANCIAL', 'Financier'), ('OPERATIONS', 'Opérations')], db_index=True, max_length=20, verbose_name='Type de rapport'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', '-generated_at'], name='reporting_r_report__ed56fc_idx'),
        ),
        migrations.AddField(
            model_name='reportline',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='reporting.report', verbose_name='Rapport'),
        ),
        migrations.AddIndex(
            model_name='reportline',
            index=models.Index(fields=['report', '-created_at'], name='reporting_r_report__aa1f3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportline',
            unique_together={('report', 'metric_name')},
        ),
    ]
