# Generated by Django 6.0.2 on 2026-03-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('RAW_MATERIALS', 'Matières premières'), ('FINISHED_GOODS', 'Produits finis'), ('SPARE_PARTS', 'Pièces détachées')], default='RAW_MATERIALS', max_length=20, verbose_name='Catégorie')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('minimum_quantity', models.PositiveIntegerField(default=10, verbose_name='Quantité minimale')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('last_restock', models.DateField(blank=True, null=True, verbose_name='Dernier réapprovisionnement')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Fournisseur')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Localisation')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['name'],
            },
        ),
    ]
