# Generated by Django 6.0.2 on 2026-05-13 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('AJUSTEMENT', 'Ajustement'), ('INVENTAIRE', 'Inventaire')], db_index=True, max_length=20, verbose_name='Type de mouvement')),
                ('quantity_before', models.PositiveIntegerField(verbose_name='Quantité avant')),
                ('quantity_after', models.PositiveIntegerField(verbose_name='Quantité après')),
                ('quantity_changed', models.IntegerField(verbose_name='Quantité modifiée')),
                ('reason', models.TextField(blank=True, verbose_name='Raison')),
                ('reference_type', models.CharField(blank=True, help_text='ex: COMMANDE, PRODUCTION', max_length=50, verbose_name='Type de référence')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de référence')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('RAW_MATERIALS', 'Matières premières'), ('FINISHED_GOODS', 'Produits finis'), ('SPARE_PARTS', 'Pièces détachées')], db_index=True, default='RAW_MATERIALS', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sku',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='SKU'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['category', 'quantity'], name='stock_stock_categor_4a0ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['quantity'], name='stock_stock_quantit_ffb26c_idx'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.stock', verbose_name='Stock'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock', '-created_at'], name='stock_stock_stock_i_e17bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='stock_stock_movemen_cbf66e_idx'),
        ),
    ]
