# Generated by Django 6.0.2 on 2026-05-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='order_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Numéro de commande'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('IN_PRODUCTION', 'En production'), ('READY', 'Prête'), ('SHIPPED', 'Expédiée'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['client', 'status'], name='commandes_c_client__08d43d_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['status', '-order_date'], name='commandes_c_status_7e25fe_idx'),
        ),
    ]
