# Generated by Django 6.0.2 on 2026-03-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la ressource')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('resource_type', models.CharField(choices=[('EQUIPMENT', 'Équipement'), ('PERSONNEL', 'Personnel'), ('FACILITY', 'Installation'), ('SOFTWARE', 'Logiciel')], max_length=20, verbose_name='Type de ressource')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('IN_USE', 'En utilisation'), ('MAINTENANCE', 'Maintenance'), ('UNAVAILABLE', 'Indisponible')], default='AVAILABLE', max_length=20, verbose_name='Statut')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Localisation')),
                ('capacity', models.CharField(blank=True, max_length=255, verbose_name='Capacité')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name="Date d'acquisition")),
                ('maintenance_date', models.DateField(blank=True, null=True, verbose_name='Dernier entretien')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['name'],
            },
        ),
    ]
